project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Hello, I'm Rui"
  site-url: https://chizapoth.github.io
  favicon: misc/info/favicon.png
  repo-url: https://github.com/chizapoth/chizapoth.github.io
  repo-actions: [edit, issue]
  
  page-footer: 
    left: "&copy; Copyright 2025, Xueyu Rui"
    right: 
      - icon: github
        href: https://github.com/chizapoth/chizapoth.github.io

  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Publications"
        href: publications/publications.qmd
      
      - text: "Learning"
        href: learning/learning.qmd
        
      - text: "About me"
        href: about_me.qmd
        
      #- text: "CV"
      #  href: misc/info/CV-CZ-2407.pdf


format:
  html:
    theme: styles.scss


